"""Add approval and payment fields to Posting

Revision ID: 0c5c0a379341
Revises: 3c6ec78e349d
Create Date: 2026-09-18 22:36:04.676002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5c0a379341'
down_revision = '3c6ec78e349d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_column('audience')
        batch_op.drop_column('color_code')
        batch_op.drop_column('event_scope')

    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_confirmed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('payment_confirmed')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('is_approved')

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_scope', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('color_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('audience', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
