"""add content planning columns to calendar_events

Revision ID: 3c6ec78e349d
Revises: b8722710fb19
Create Date: 2026-06-13 20:17:53.855452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6ec78e349d'
down_revision = 'b8722710fb19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_scope', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('audience', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('color_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_column('color_code')
        batch_op.drop_column('audience')
        batch_op.drop_column('event_scope')

    # ### end Alembic commands ###
