"""add escalated flag to weekly_report

Revision ID: b8722710fb19
Revises: 2311ef9bb1dc
Create Date: 2026-06-13 19:28:17.609361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8722710fb19'
down_revision = '2311ef9bb1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escalated', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('escalated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('escalated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['escalated_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('escalated_by_id')
        batch_op.drop_column('escalated_at')
        batch_op.drop_column('escalated')

    # ### end Alembic commands ###
